<?php

/**
 * @file
 * car.install
 */

/**
 * Implements hook_schema().
 */
function car_schema() {
  $schema['car'] = array(
  'description' => 'Base table for entity Car',
    'fields' => array(
      'car_id' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'description' => "The car record id",
      ),
      'title' => array(
        'type' => 'varchar',
        'length' => 256,
        'default' => NULL,
        'description' => "The title of the car.",
      ),
      'make' => array(
        'type' => 'varchar',
        'length' => 128,
        'default' => NULL,
        'description' => "The maker of the car.",
      ),
      'model' => array(
        'type' => 'varchar',
        'length' => 128,
        'default' => NULL,
        'description' => "The model of the car.",
      ),
      'color' => array(
        'type' => 'varchar',
        'length' => 128,
        'default' => NULL,
        'description' => "The color of the car.",
      ),
      'top_speed' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => "Top speed of the car in MPH.",
      ),
      'price' => array(
        'type' => 'float',
        'not null' => TRUE,
        'default' => 0,
        'description' => "The price of the car.",
      ),
      'categoria' => array(
        'type' => 'int',
        'length' => 2,
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'primary key' => array('car_id'),
  );

  return $schema;
}

 /**
     * Implements hook_enable().
     */

    function car_enable() {
      $vocabulary = taxonomy_vocabulary_load(variable_get('photoshare_categories_vocabulary', 0));
      if (!$vocabulary) {
        $category = array(
          'name' => t('Categories'),
          'machine_name' => 'photoshare_categories',
          'description' => t('Photoshare categories vocabulary'),
          'hierarchy' => 1,
          'module' => 'photoshare',
        );
        $vocabulary = (object) $category;
        taxonomy_vocabulary_save($vocabulary);
        variable_set('photoshare_categories_vocabulary', $vocabulary->vid);
      }

      $vocabulary = taxonomy_vocabulary_load(variable_get('products2', 0));
      if (!$vocabulary) {
        $category = array(
          'name' => t('productos2'),
          'machine_name' => 'products2',
          'description' => t('products2 categories vocabulary'),
          'hierarchy' => 1,
          'module' => 'products2',
        );
        $vocabulary = (object) $category;
        taxonomy_vocabulary_save($vocabulary);
        variable_set('products2', $vocabulary->vid);
      }
    }

